version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  discountdb:
    container_name: discountdb
    environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=admin987
     - POSTGRES_DB=DiscountDb
    restart: always
    ports:
     - "5432:5432"
    volumes:
     -  postgres_data:/var/lib/postgresql/data/

  pgAdmin:
     container_name: pgAdmin
     environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
     restart: always
     ports:
      - "5050:80"
     volumes:
      - pgAdmin_data:/root/.pgadmin
       
     
    


  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on: # این کانتینر به چه کانتینر دیگه وابسته است
      - catlogdb
    ports:
      - "8000:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSetting:connectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=discount.grpc"
    depends_on:
      - basketdb
    ports:
      - "8001:80"




  discount.api:
    container_name: discount.api  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSetting:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin987"
    depends_on:
      - discountdb
    ports:
      - "8002:80"


  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSetting:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin987"
    depends_on:
      - discountdb
    ports:
      - "8003:80"

